
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ws-producto
          uri: http://localhost:8005/productos
          predicates:
            - Path=/productos/**
  #application:
  #  name: registry-service          