
server:
  port: 8083
eureka:
  client:
#    registryWithEureka: true
#    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8082/eureka/
#    instance:
#      hostname: localhost  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ws-producto
#          uri: http://localhost:8005/productos
          uri: lb//ws-producto
          predicates:
            - Path=/productos/**
  #application:
  #  name: registry-service          