server:
  port: 8005
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bootcamp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
